#ActorName:El Malvado brujo Klevo #ActorImage:MagoKlevo0 #layout:Default
-> intro

== intro ==

ugh...
¿Como es posible?
¿Como sabes demaciado?
Puede que me hayas derrotado esta vez explorador, pero creeme...
Volvere...
Y la proxima vez no podras detenerme...

--> END